name: Test PR

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup
        uses: ./.github/actions/setup

      - name: test
        run: pnpm test -- -- --changed origin/${{ github.base_ref }} --passWithNoTests
